export const VISUAL_TOKENS = {
  environment: {
    void: '#050509',
    wallDeep: '#10111b',
    wall: '#171b2a',
    wallLight: '#232a3e',
    floorDeep: '#1f315f',
    floor: '#34518f',
    floorLight: '#506fbb',
    moon: '#d8e7ff',
  },
  actor: {
    outline: '#17101f',
    skinShadow: '#9a5a50',
    skin: '#e7a06f',
    skinLight: '#ffd39a',
    pajamasShadow: '#1e7890',
    pajamas: '#48c7c8',
    pajamasLight: '#84ece3',
    slippers: '#d765ad',
  },
  interactive: {
    outline: '#21172d',
    shadow: '#49305f',
    base: '#d45aaa',
    light: '#f08ac8',
    focus: '#f1d75c',
    focusLight: '#fff09a',
  },
  feedback: {
    quiet: '#55b66a',
    quietDark: '#326f40',
    energy: '#61ca72',
    noise: '#e75a65',
    noiseDark: '#7d303b',
    rush: '#f1d75c',
    danger: '#f0525f',
    success: '#70d887',
    failure: '#e64f62',
    neutral: '#48d6d2',
  },
  ui: {
    panel: '#0c0912',
    panelRaised: '#171326',
    panelEdge: '#49305f',
    ink: '#f7f0cf',
    inkMuted: '#9b92ae',
    cyan: '#48d6d2',
    cyanDark: '#257f82',
    magenta: '#d45aaa',
    magentaDark: '#7e356d',
    yellow: '#f1d75c',
    yellowDark: '#8e7c34',
  },
  fx: {
    shock: '#fff09a',
    dust: '#9b92ae',
    sparkle: '#fff2a3',
    motion: '#84ece3',
    impact: '#f0525f',
    sleep: '#8dd9ff',
  },
} as const;

export const PIXEL_ART_POLICY = {
  logicalWorldSize: 128,
  baseSpriteScale: 1,
  integerPlacementOnly: true,
  smoothing: false,
  outlinePixels: 1,
  interactiveContrastMinimumSteps: 2,
} as const;

export const VISUAL_VALUE_ORDER = [
  'environment',
  'secondary-props',
  'interactive-objects',
  'wally',
  'fx',
] as const;

export const FX_GRAMMAR = [
  'shock',
  'noise',
  'dust',
  'sparkle',
  'sleep',
  'motion-streak',
  'impact',
] as const;

// Compatibility aliases while the old renderer is progressively removed.
// New presentation code should prefer VISUAL_TOKENS.
export const RETRO_PALETTE = {
  void: VISUAL_TOKENS.environment.void,
  panel: VISUAL_TOKENS.ui.panel,
  panelRaised: VISUAL_TOKENS.ui.panelRaised,
  ink: VISUAL_TOKENS.ui.ink,
  cyan: VISUAL_TOKENS.ui.cyan,
  cyanDark: VISUAL_TOKENS.ui.cyanDark,
  blue: VISUAL_TOKENS.environment.floor,
  blueDark: VISUAL_TOKENS.environment.floorDeep,
  magenta: VISUAL_TOKENS.ui.magenta,
  magentaDark: VISUAL_TOKENS.ui.magentaDark,
  purple: '#774e9e',
  purpleDark: VISUAL_TOKENS.ui.panelEdge,
  yellow: VISUAL_TOKENS.ui.yellow,
  yellowDark: VISUAL_TOKENS.ui.yellowDark,
  red: VISUAL_TOKENS.feedback.noise,
  redDark: VISUAL_TOKENS.feedback.noiseDark,
  green: VISUAL_TOKENS.feedback.quiet,
  greenDark: VISUAL_TOKENS.feedback.quietDark,
  orange: '#df8847',
  orangeDark: '#844f2c',
  shadow: VISUAL_TOKENS.actor.outline,
  moon: VISUAL_TOKENS.environment.moon,
} as const;
